### ISSUE TITLE
Disable goggles per-buffer

### ISSUE THREAD

**Issue by duckwork** [minad/goggles#3]
For example, I'd like to disable goggles in the magit-status buffer.  It could be implemented as a list of regexes, or maybe a hook to disable goggles per-buffer.

**Comment by minad** [comment]
Yes, this has been reported before. How does volatile highlights solve this? Are these buffer local? I don't have time to work on this myself right now, but look at PR #2 for an attempt.

**Comment by duckwork** [comment]
Okay thanks, I will research :) and get back to you!

**Comment by yantar92** [comment]
Thanks!

**Comment by minad** [comment]
@yantar92 Note that I could not get the buffer local advices to work via add-function. But goggles--advice is most minimal now.
