### ISSUE TITLE
goggles is blinking my vterm

### ISSUE THREAD

**Issue by DamienCassou** [minad/goggles#4]
Starting with [this vterm commit](https://github.com/akermu/emacs-libvterm/commit/4afb7d0681ea79c9224b26976e545bb3a4a16370), googles is blinking my vterm buffer. Here are 2 videos demonstrating it, one with powerline-go, one without:

https://user-images.githubusercontent.com/217543/107028800-58fedc00-67ae-11eb-9600-04c31da61579.mp4

https://user-images.githubusercontent.com/217543/107028805-5a300900-67ae-11eb-8b89-ffa7ee5826f4.mp4

Workaround: deactivate goggles.

/cc the author of the vterm's commit @jixiuf

**Comment by minad** [comment]
Yes, things like this can happen. There are multiple major modes where you may not want to have goggles. At some point buffer-local googles have to be implemented, see #3. I would welcome a PR implementing this.

**Comment by jixiuf** [comment]
vterm is not suitable for this package , vterm would flush the full screen sometimes.

**Comment by minad** [comment]
Yes, surely it is not. The problem is purely on the side of goggles, I acknowledge that. Goggles should actually be buffer-local as I wrote above.
