### ISSUE TITLE
Define goggle for goto-line

### ISSUE THREAD

**Issue by yves-biener** [minad/goggles#6]
Hello minad,

first thank you for the packages you created for emacs. They improve my workflow and my emacs experience tremendous, but I can't figure out how to add the built-in `goto-line` command as a goggle to enable pulsing after jumping to a given line using `<M-g g>`.

I tried the following without success:
`(with-eval-after-load 'goggles
    (require 'goggles)
    (goggles-define goto goto-line))`
Can you help me to fix my problem?

Regards Yves

**Comment by minad** [comment]
Goggles only pulses on *modifications*. goto-line is therefore not supported by goggles. There are alternatives like beacon-mode you can try. You may also check out consult-goto-line in case you use Consult. There you can add a pulse function to the consult-after-jump-hook.
