### ISSUE TITLE
Support for transforming operations like `paredit-slurp-forward` `transpose-words` `shell-command-on-region`...

### ISSUE THREAD

**Issue by shenlebantongying** [minad/goggles#7]
When I use the goggles, I always feel something is missing, and finally the missing part come to my mind:

It is the operations that transform texts should get some pulsed.

- `paredit-forward-slurp-sexp` is especially useful. When the ending brackets are too much, I do want to see which part is eaten by "slurping".
- `shell-cmd-on-region` -> it has a `replace` option. When replacing is happening -> which part come after?

I am not sure if this is implementable since the boundaries of those operations is hard to tell? (maybe?) and there doesn't seem to have a generic pattern.

**Comment by shenlebantongying** [comment]
My bad, title should be `paredit-forward-slurp-sexp`

**Comment by Kaligule** [comment]
This issue was closed "as completed". @shenlebantongying can you elaborate in which way this was completed?
For me the this does not highlight anything when using `transpose-words` or `shell-command-on-region`.

**Comment by shenlebantongying** [comment]
Sorry, I have forgotten the exact details, but

I switched to pulsar after closing this https://protesilaos.com/emacs/pulsar , and now I don't use either :sweat_smile: 

I vaguely remember that the flash cannot be implemented efficiently or cannot be implemented in a happy way based on last year's code of `goggles`.

**Comment by minad** [comment]
`transpose-words` etc works now, but `shell-command-on-region` doesn't transform the region and as such isn't a good fit for goggles.

**Comment by Kaligule** [comment]
Thanks
